export const FACEBOOKADS_RESOURCE_CONTENT_TEXT_PATH_ROUTES = {
  CREATE_CONTENT_TEXT: '/create',
  GET_ALL_CONTENT_TEXTS: '/get-all',
  GET_CONTENT_TEXT_BY_ID: '/:id',
  UPDATE_CONTENT_TEXT: '/:id',
  DELETE_CONTENT_TEXT: '/:id'
}
